name: flutter_pizza_example
description: A flutter example to implement flutter_pizza.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_icons:
  get: 
  flutter_pizza:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/flavors.json
    - assets/logo.png
    - assets/images/tray.png
    - assets/images/chicken.png
    - assets/images/chocolate.png
    - assets/images/endive.png
    - assets/images/neapolitan.png
    - assets/images/pepperoni.png
    - assets/images/shrimp.png